api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']

    # The title of the API.
    title: 'DevWebProjet API'
    # The version of the API.
    version: '1.0.0'
    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false
            # The default number of items per page.
            items_per_page: 5
            # To allow the client to enable or disable the pagination.
            client_enabled : true
            # To allow the client to set the number of items per page.
            client_items_per_page: true
            # The default name of the parameter handling the page number.
            items_per_page_parameter_name: 'count'

    doctrine:
        # To enable or disable Doctrine ORM support.
        enabled: true

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
                mime_types: ['application/ld+json']

        json:
                mime_types: ['application/json']

        html:
            mime_types: ['text/html']
