security:
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #autorise l'authentification d'ulisiateur sans être authentifié
        registration:
            pattern:  ^/api/users
            stateless: true
            anonymous: true
            methods : [POST]
        #vérifie l'utilisateur
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            #tout ce qui se trouve sous /api doit être authentifié
        api:
            pattern:   ^/api
            stateless: true
            #Autorise l'accès au infos de l'api
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true
            #provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https}
        - { path: ^/api/clients, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/commande_montures, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/commande_verres, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        - { path: ^/api/corrections, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/etat_commandes, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/magasins, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/montures, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/prescripteurs, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/stocks, roles: IS_AUTHENTICATED_FULLY, requires_channel: https}
        - { path: ^/api/verres, roles: IS_AUTHENTICATED_FULLY , requires_channel: https}
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY , methods:[POST,GET, PUT, DELETE], requires_channel: https}

