<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFzxkZA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFzxkZA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFzxkZA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFzxkZA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQFzxkZA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QFzxkZA',
    'container.build_id' => 'd1d29320',
    'container.build_time' => 1584464900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFzxkZA');
