<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYKJPq86\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYKJPq86/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYKJPq86.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYKJPq86\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYKJPq86\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YKJPq86',
    'container.build_id' => '457c050e',
    'container.build_time' => 1586359645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYKJPq86');
