<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLMaVKQ5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLMaVKQ5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLMaVKQ5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLMaVKQ5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLMaVKQ5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LMaVKQ5',
    'container.build_id' => '79be335c',
    'container.build_time' => 1586389892,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLMaVKQ5');
